parameters:
#    phpist_user.example.class: Phpist\Bundle\UserBundle\Example

services:
#    phpist_user.example:
#        class: %phpist_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
