services:
  phpist_event.repository.event_repository:
        class:           Phpist\EventBundle\Repository\EventRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method:  getRepository
        arguments:
            - PhpistEventBundle:Event

  phpist_event.repository.session_repository:
        class:           Phpist\EventBundle\Repository\SessionRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method:  getRepository
        arguments:
            - PhpistEventBundle:Session
