parameters:
#    phpist_event.example.class: Phpist\Bundle\EventBundle\Example

services:
#    phpist_event.example:
#        class: %phpist_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
